package com.novare.minet.util;

public enum MenuContext {

	WELCOME, SIGNUP, LOGIN,

	PRODUCT, CREATE_PRODUCT, PRODUCT_LIST, EDIT_PRODUCT, DELETE_PRODUCT,SEARCH_PRODUCT,

	INVENTORY, INVENTORY_LIST, CREATE_ORDER, ORDER_LIST, PENDING_ORDERS, SEARCH_ORDER,

	SUPPLIERS, CREATE_SUPPLY, EDIT_SUPPLY, DELETE_SUPPLY, SUPPLY_LIST,

	REPORTS, BEST_SELLING_PRODUCTS, PRODUCT_PROFITS,

	TRANSACTION_LIST,

	CASHIER, START_TRANSACTION, RETURN_PRODUCT,

	ADMIN, PAYMENTS, CASHFLOW, PROFITS, ORDER_HISTORY,

	MANAGER,  REVIEW_INVENTORY,

	LOGOUT;

}
