package com.novare.minet.util;

public enum MenuContext {

	WELCOME, SIGNUP, LOGIN,

	PRODUCT, CREATE_PRODUCT, PRODUCT_LIST, EDIT_PRODUCT, DELETE_PRODUCT, SEARCH_PRODUCT,

	INVENTORY, CREATE_INVENTORY, EDIT_INVENTORY, DELETE_INVENTORY, INVENTORY_LIST,

	SUPPLIERS, CREATE_SUPPLIER, EDIT_SUPPLIER, DELETE_SUPPLIER, SUPPLIER_LIST,

	ORDER, CREATE_ORDER, DELETE_ORDER, EDIT_ORDER, ORDER_LIST, PENDING_ORDERS, SEARCH_ORDER, ORDER_HISTORY,

	CASHIER, START_TRANSACTION, RETURN_PRODUCT, TRANSACTION_LIST,

	ADMIN, PAYMENTS, CASHFLOW, PROFITS, REPORTS, BEST_SELLING_PRODUCTS, PRODUCT_PROFITS,

	MANAGER, REVIEW_INVENTORY,

	LOGOUT;

}
